/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthSincronizadorRouteImport } from './routes/_auth/sincronizador'
import { Route as AuthRelatoriosProdutividadeRouteImport } from './routes/_auth/relatorios/produtividade'
import { Route as AuthRelatoriosConsumoPlanosRouteImport } from './routes/_auth/relatorios/consumo-planos'
import { Route as AuthRelatoriosClienteRouteImport } from './routes/_auth/relatorios/cliente'
import { Route as AuthRelatoriosApontamentosRouteImport } from './routes/_auth/relatorios/apontamentos'
import { Route as AuthDashboardsSuporteRouteImport } from './routes/_auth/dashboards/suporte'
import { Route as AuthDashboardsOnboardingRouteImport } from './routes/_auth/dashboards/onboarding'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSincronizadorRoute = AuthSincronizadorRouteImport.update({
  id: '/sincronizador',
  path: '/sincronizador',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRelatoriosProdutividadeRoute =
  AuthRelatoriosProdutividadeRouteImport.update({
    id: '/relatorios/produtividade',
    path: '/relatorios/produtividade',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthRelatoriosConsumoPlanosRoute =
  AuthRelatoriosConsumoPlanosRouteImport.update({
    id: '/relatorios/consumo-planos',
    path: '/relatorios/consumo-planos',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthRelatoriosClienteRoute = AuthRelatoriosClienteRouteImport.update({
  id: '/relatorios/cliente',
  path: '/relatorios/cliente',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRelatoriosApontamentosRoute =
  AuthRelatoriosApontamentosRouteImport.update({
    id: '/relatorios/apontamentos',
    path: '/relatorios/apontamentos',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthDashboardsSuporteRoute = AuthDashboardsSuporteRouteImport.update({
  id: '/dashboards/suporte',
  path: '/dashboards/suporte',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardsOnboardingRoute =
  AuthDashboardsOnboardingRouteImport.update({
    id: '/dashboards/onboarding',
    path: '/dashboards/onboarding',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/sincronizador': typeof AuthSincronizadorRoute
  '/dashboards/onboarding': typeof AuthDashboardsOnboardingRoute
  '/dashboards/suporte': typeof AuthDashboardsSuporteRoute
  '/relatorios/apontamentos': typeof AuthRelatoriosApontamentosRoute
  '/relatorios/cliente': typeof AuthRelatoriosClienteRoute
  '/relatorios/consumo-planos': typeof AuthRelatoriosConsumoPlanosRoute
  '/relatorios/produtividade': typeof AuthRelatoriosProdutividadeRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/sincronizador': typeof AuthSincronizadorRoute
  '/': typeof AuthIndexRoute
  '/dashboards/onboarding': typeof AuthDashboardsOnboardingRoute
  '/dashboards/suporte': typeof AuthDashboardsSuporteRoute
  '/relatorios/apontamentos': typeof AuthRelatoriosApontamentosRoute
  '/relatorios/cliente': typeof AuthRelatoriosClienteRoute
  '/relatorios/consumo-planos': typeof AuthRelatoriosConsumoPlanosRoute
  '/relatorios/produtividade': typeof AuthRelatoriosProdutividadeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/sincronizador': typeof AuthSincronizadorRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/dashboards/onboarding': typeof AuthDashboardsOnboardingRoute
  '/_auth/dashboards/suporte': typeof AuthDashboardsSuporteRoute
  '/_auth/relatorios/apontamentos': typeof AuthRelatoriosApontamentosRoute
  '/_auth/relatorios/cliente': typeof AuthRelatoriosClienteRoute
  '/_auth/relatorios/consumo-planos': typeof AuthRelatoriosConsumoPlanosRoute
  '/_auth/relatorios/produtividade': typeof AuthRelatoriosProdutividadeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sincronizador'
    | '/dashboards/onboarding'
    | '/dashboards/suporte'
    | '/relatorios/apontamentos'
    | '/relatorios/cliente'
    | '/relatorios/consumo-planos'
    | '/relatorios/produtividade'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/sincronizador'
    | '/'
    | '/dashboards/onboarding'
    | '/dashboards/suporte'
    | '/relatorios/apontamentos'
    | '/relatorios/cliente'
    | '/relatorios/consumo-planos'
    | '/relatorios/produtividade'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/sincronizador'
    | '/_auth/'
    | '/_auth/dashboards/onboarding'
    | '/_auth/dashboards/suporte'
    | '/_auth/relatorios/apontamentos'
    | '/_auth/relatorios/cliente'
    | '/_auth/relatorios/consumo-planos'
    | '/_auth/relatorios/produtividade'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sincronizador': {
      id: '/_auth/sincronizador'
      path: '/sincronizador'
      fullPath: '/sincronizador'
      preLoaderRoute: typeof AuthSincronizadorRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/relatorios/produtividade': {
      id: '/_auth/relatorios/produtividade'
      path: '/relatorios/produtividade'
      fullPath: '/relatorios/produtividade'
      preLoaderRoute: typeof AuthRelatoriosProdutividadeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/relatorios/consumo-planos': {
      id: '/_auth/relatorios/consumo-planos'
      path: '/relatorios/consumo-planos'
      fullPath: '/relatorios/consumo-planos'
      preLoaderRoute: typeof AuthRelatoriosConsumoPlanosRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/relatorios/cliente': {
      id: '/_auth/relatorios/cliente'
      path: '/relatorios/cliente'
      fullPath: '/relatorios/cliente'
      preLoaderRoute: typeof AuthRelatoriosClienteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/relatorios/apontamentos': {
      id: '/_auth/relatorios/apontamentos'
      path: '/relatorios/apontamentos'
      fullPath: '/relatorios/apontamentos'
      preLoaderRoute: typeof AuthRelatoriosApontamentosRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboards/suporte': {
      id: '/_auth/dashboards/suporte'
      path: '/dashboards/suporte'
      fullPath: '/dashboards/suporte'
      preLoaderRoute: typeof AuthDashboardsSuporteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboards/onboarding': {
      id: '/_auth/dashboards/onboarding'
      path: '/dashboards/onboarding'
      fullPath: '/dashboards/onboarding'
      preLoaderRoute: typeof AuthDashboardsOnboardingRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthSincronizadorRoute: typeof AuthSincronizadorRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthDashboardsOnboardingRoute: typeof AuthDashboardsOnboardingRoute
  AuthDashboardsSuporteRoute: typeof AuthDashboardsSuporteRoute
  AuthRelatoriosApontamentosRoute: typeof AuthRelatoriosApontamentosRoute
  AuthRelatoriosClienteRoute: typeof AuthRelatoriosClienteRoute
  AuthRelatoriosConsumoPlanosRoute: typeof AuthRelatoriosConsumoPlanosRoute
  AuthRelatoriosProdutividadeRoute: typeof AuthRelatoriosProdutividadeRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSincronizadorRoute: AuthSincronizadorRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthDashboardsOnboardingRoute: AuthDashboardsOnboardingRoute,
  AuthDashboardsSuporteRoute: AuthDashboardsSuporteRoute,
  AuthRelatoriosApontamentosRoute: AuthRelatoriosApontamentosRoute,
  AuthRelatoriosClienteRoute: AuthRelatoriosClienteRoute,
  AuthRelatoriosConsumoPlanosRoute: AuthRelatoriosConsumoPlanosRoute,
  AuthRelatoriosProdutividadeRoute: AuthRelatoriosProdutividadeRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
