/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthSincronizadorRouteImport } from './routes/_auth/sincronizador'
import { Route as AuthEquipesRouteImport } from './routes/_auth/equipes'
import { Route as AuthConfiguracoesRouteImport } from './routes/_auth/configuracoes'
import { Route as AuthCategoriasRouteImport } from './routes/_auth/categorias'
import { Route as AuthRelatoriosProdutividadeRouteImport } from './routes/_auth/relatorios/produtividade'
import { Route as AuthRelatoriosMovimentacaoDiariaRouteImport } from './routes/_auth/relatorios/movimentacao-diaria'
import { Route as AuthRelatoriosConsumoPlanosRouteImport } from './routes/_auth/relatorios/consumo-planos'
import { Route as AuthRelatoriosClienteRouteImport } from './routes/_auth/relatorios/cliente'
import { Route as AuthRelatoriosApontamentosProjetoRouteImport } from './routes/_auth/relatorios/apontamentos-projeto'
import { Route as AuthRelatoriosApontamentosRouteImport } from './routes/_auth/relatorios/apontamentos'
import { Route as AuthDashboardsSuporteRouteImport } from './routes/_auth/dashboards/suporte'
import { Route as AuthDashboardsOnboardingRouteImport } from './routes/_auth/dashboards/onboarding'
import { Route as AuthRelatoriosTicketsTicketIdRouteImport } from './routes/_auth/relatorios/tickets.$ticketId'
import { Route as AuthRelatoriosClientesClientIdRouteImport } from './routes/_auth/relatorios/clientes.$clientId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSincronizadorRoute = AuthSincronizadorRouteImport.update({
  id: '/sincronizador',
  path: '/sincronizador',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEquipesRoute = AuthEquipesRouteImport.update({
  id: '/equipes',
  path: '/equipes',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConfiguracoesRoute = AuthConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCategoriasRoute = AuthCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRelatoriosProdutividadeRoute =
  AuthRelatoriosProdutividadeRouteImport.update({
    id: '/relatorios/produtividade',
    path: '/relatorios/produtividade',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthRelatoriosMovimentacaoDiariaRoute =
  AuthRelatoriosMovimentacaoDiariaRouteImport.update({
    id: '/relatorios/movimentacao-diaria',
    path: '/relatorios/movimentacao-diaria',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthRelatoriosConsumoPlanosRoute =
  AuthRelatoriosConsumoPlanosRouteImport.update({
    id: '/relatorios/consumo-planos',
    path: '/relatorios/consumo-planos',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthRelatoriosClienteRoute = AuthRelatoriosClienteRouteImport.update({
  id: '/relatorios/cliente',
  path: '/relatorios/cliente',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRelatoriosApontamentosProjetoRoute =
  AuthRelatoriosApontamentosProjetoRouteImport.update({
    id: '/relatorios/apontamentos-projeto',
    path: '/relatorios/apontamentos-projeto',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthRelatoriosApontamentosRoute =
  AuthRelatoriosApontamentosRouteImport.update({
    id: '/relatorios/apontamentos',
    path: '/relatorios/apontamentos',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthDashboardsSuporteRoute = AuthDashboardsSuporteRouteImport.update({
  id: '/dashboards/suporte',
  path: '/dashboards/suporte',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardsOnboardingRoute =
  AuthDashboardsOnboardingRouteImport.update({
    id: '/dashboards/onboarding',
    path: '/dashboards/onboarding',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthRelatoriosTicketsTicketIdRoute =
  AuthRelatoriosTicketsTicketIdRouteImport.update({
    id: '/relatorios/tickets/$ticketId',
    path: '/relatorios/tickets/$ticketId',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthRelatoriosClientesClientIdRoute =
  AuthRelatoriosClientesClientIdRouteImport.update({
    id: '/relatorios/clientes/$clientId',
    path: '/relatorios/clientes/$clientId',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/categorias': typeof AuthCategoriasRoute
  '/configuracoes': typeof AuthConfiguracoesRoute
  '/equipes': typeof AuthEquipesRoute
  '/sincronizador': typeof AuthSincronizadorRoute
  '/dashboards/onboarding': typeof AuthDashboardsOnboardingRoute
  '/dashboards/suporte': typeof AuthDashboardsSuporteRoute
  '/relatorios/apontamentos': typeof AuthRelatoriosApontamentosRoute
  '/relatorios/apontamentos-projeto': typeof AuthRelatoriosApontamentosProjetoRoute
  '/relatorios/cliente': typeof AuthRelatoriosClienteRoute
  '/relatorios/consumo-planos': typeof AuthRelatoriosConsumoPlanosRoute
  '/relatorios/movimentacao-diaria': typeof AuthRelatoriosMovimentacaoDiariaRoute
  '/relatorios/produtividade': typeof AuthRelatoriosProdutividadeRoute
  '/relatorios/clientes/$clientId': typeof AuthRelatoriosClientesClientIdRoute
  '/relatorios/tickets/$ticketId': typeof AuthRelatoriosTicketsTicketIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/categorias': typeof AuthCategoriasRoute
  '/configuracoes': typeof AuthConfiguracoesRoute
  '/equipes': typeof AuthEquipesRoute
  '/sincronizador': typeof AuthSincronizadorRoute
  '/': typeof AuthIndexRoute
  '/dashboards/onboarding': typeof AuthDashboardsOnboardingRoute
  '/dashboards/suporte': typeof AuthDashboardsSuporteRoute
  '/relatorios/apontamentos': typeof AuthRelatoriosApontamentosRoute
  '/relatorios/apontamentos-projeto': typeof AuthRelatoriosApontamentosProjetoRoute
  '/relatorios/cliente': typeof AuthRelatoriosClienteRoute
  '/relatorios/consumo-planos': typeof AuthRelatoriosConsumoPlanosRoute
  '/relatorios/movimentacao-diaria': typeof AuthRelatoriosMovimentacaoDiariaRoute
  '/relatorios/produtividade': typeof AuthRelatoriosProdutividadeRoute
  '/relatorios/clientes/$clientId': typeof AuthRelatoriosClientesClientIdRoute
  '/relatorios/tickets/$ticketId': typeof AuthRelatoriosTicketsTicketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/categorias': typeof AuthCategoriasRoute
  '/_auth/configuracoes': typeof AuthConfiguracoesRoute
  '/_auth/equipes': typeof AuthEquipesRoute
  '/_auth/sincronizador': typeof AuthSincronizadorRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/dashboards/onboarding': typeof AuthDashboardsOnboardingRoute
  '/_auth/dashboards/suporte': typeof AuthDashboardsSuporteRoute
  '/_auth/relatorios/apontamentos': typeof AuthRelatoriosApontamentosRoute
  '/_auth/relatorios/apontamentos-projeto': typeof AuthRelatoriosApontamentosProjetoRoute
  '/_auth/relatorios/cliente': typeof AuthRelatoriosClienteRoute
  '/_auth/relatorios/consumo-planos': typeof AuthRelatoriosConsumoPlanosRoute
  '/_auth/relatorios/movimentacao-diaria': typeof AuthRelatoriosMovimentacaoDiariaRoute
  '/_auth/relatorios/produtividade': typeof AuthRelatoriosProdutividadeRoute
  '/_auth/relatorios/clientes/$clientId': typeof AuthRelatoriosClientesClientIdRoute
  '/_auth/relatorios/tickets/$ticketId': typeof AuthRelatoriosTicketsTicketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/categorias'
    | '/configuracoes'
    | '/equipes'
    | '/sincronizador'
    | '/dashboards/onboarding'
    | '/dashboards/suporte'
    | '/relatorios/apontamentos'
    | '/relatorios/apontamentos-projeto'
    | '/relatorios/cliente'
    | '/relatorios/consumo-planos'
    | '/relatorios/movimentacao-diaria'
    | '/relatorios/produtividade'
    | '/relatorios/clientes/$clientId'
    | '/relatorios/tickets/$ticketId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/categorias'
    | '/configuracoes'
    | '/equipes'
    | '/sincronizador'
    | '/'
    | '/dashboards/onboarding'
    | '/dashboards/suporte'
    | '/relatorios/apontamentos'
    | '/relatorios/apontamentos-projeto'
    | '/relatorios/cliente'
    | '/relatorios/consumo-planos'
    | '/relatorios/movimentacao-diaria'
    | '/relatorios/produtividade'
    | '/relatorios/clientes/$clientId'
    | '/relatorios/tickets/$ticketId'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/categorias'
    | '/_auth/configuracoes'
    | '/_auth/equipes'
    | '/_auth/sincronizador'
    | '/_auth/'
    | '/_auth/dashboards/onboarding'
    | '/_auth/dashboards/suporte'
    | '/_auth/relatorios/apontamentos'
    | '/_auth/relatorios/apontamentos-projeto'
    | '/_auth/relatorios/cliente'
    | '/_auth/relatorios/consumo-planos'
    | '/_auth/relatorios/movimentacao-diaria'
    | '/_auth/relatorios/produtividade'
    | '/_auth/relatorios/clientes/$clientId'
    | '/_auth/relatorios/tickets/$ticketId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sincronizador': {
      id: '/_auth/sincronizador'
      path: '/sincronizador'
      fullPath: '/sincronizador'
      preLoaderRoute: typeof AuthSincronizadorRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/equipes': {
      id: '/_auth/equipes'
      path: '/equipes'
      fullPath: '/equipes'
      preLoaderRoute: typeof AuthEquipesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/configuracoes': {
      id: '/_auth/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthConfiguracoesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/categorias': {
      id: '/_auth/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AuthCategoriasRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/relatorios/produtividade': {
      id: '/_auth/relatorios/produtividade'
      path: '/relatorios/produtividade'
      fullPath: '/relatorios/produtividade'
      preLoaderRoute: typeof AuthRelatoriosProdutividadeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/relatorios/movimentacao-diaria': {
      id: '/_auth/relatorios/movimentacao-diaria'
      path: '/relatorios/movimentacao-diaria'
      fullPath: '/relatorios/movimentacao-diaria'
      preLoaderRoute: typeof AuthRelatoriosMovimentacaoDiariaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/relatorios/consumo-planos': {
      id: '/_auth/relatorios/consumo-planos'
      path: '/relatorios/consumo-planos'
      fullPath: '/relatorios/consumo-planos'
      preLoaderRoute: typeof AuthRelatoriosConsumoPlanosRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/relatorios/cliente': {
      id: '/_auth/relatorios/cliente'
      path: '/relatorios/cliente'
      fullPath: '/relatorios/cliente'
      preLoaderRoute: typeof AuthRelatoriosClienteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/relatorios/apontamentos-projeto': {
      id: '/_auth/relatorios/apontamentos-projeto'
      path: '/relatorios/apontamentos-projeto'
      fullPath: '/relatorios/apontamentos-projeto'
      preLoaderRoute: typeof AuthRelatoriosApontamentosProjetoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/relatorios/apontamentos': {
      id: '/_auth/relatorios/apontamentos'
      path: '/relatorios/apontamentos'
      fullPath: '/relatorios/apontamentos'
      preLoaderRoute: typeof AuthRelatoriosApontamentosRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboards/suporte': {
      id: '/_auth/dashboards/suporte'
      path: '/dashboards/suporte'
      fullPath: '/dashboards/suporte'
      preLoaderRoute: typeof AuthDashboardsSuporteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboards/onboarding': {
      id: '/_auth/dashboards/onboarding'
      path: '/dashboards/onboarding'
      fullPath: '/dashboards/onboarding'
      preLoaderRoute: typeof AuthDashboardsOnboardingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/relatorios/tickets/$ticketId': {
      id: '/_auth/relatorios/tickets/$ticketId'
      path: '/relatorios/tickets/$ticketId'
      fullPath: '/relatorios/tickets/$ticketId'
      preLoaderRoute: typeof AuthRelatoriosTicketsTicketIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/relatorios/clientes/$clientId': {
      id: '/_auth/relatorios/clientes/$clientId'
      path: '/relatorios/clientes/$clientId'
      fullPath: '/relatorios/clientes/$clientId'
      preLoaderRoute: typeof AuthRelatoriosClientesClientIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthCategoriasRoute: typeof AuthCategoriasRoute
  AuthConfiguracoesRoute: typeof AuthConfiguracoesRoute
  AuthEquipesRoute: typeof AuthEquipesRoute
  AuthSincronizadorRoute: typeof AuthSincronizadorRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthDashboardsOnboardingRoute: typeof AuthDashboardsOnboardingRoute
  AuthDashboardsSuporteRoute: typeof AuthDashboardsSuporteRoute
  AuthRelatoriosApontamentosRoute: typeof AuthRelatoriosApontamentosRoute
  AuthRelatoriosApontamentosProjetoRoute: typeof AuthRelatoriosApontamentosProjetoRoute
  AuthRelatoriosClienteRoute: typeof AuthRelatoriosClienteRoute
  AuthRelatoriosConsumoPlanosRoute: typeof AuthRelatoriosConsumoPlanosRoute
  AuthRelatoriosMovimentacaoDiariaRoute: typeof AuthRelatoriosMovimentacaoDiariaRoute
  AuthRelatoriosProdutividadeRoute: typeof AuthRelatoriosProdutividadeRoute
  AuthRelatoriosClientesClientIdRoute: typeof AuthRelatoriosClientesClientIdRoute
  AuthRelatoriosTicketsTicketIdRoute: typeof AuthRelatoriosTicketsTicketIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCategoriasRoute: AuthCategoriasRoute,
  AuthConfiguracoesRoute: AuthConfiguracoesRoute,
  AuthEquipesRoute: AuthEquipesRoute,
  AuthSincronizadorRoute: AuthSincronizadorRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthDashboardsOnboardingRoute: AuthDashboardsOnboardingRoute,
  AuthDashboardsSuporteRoute: AuthDashboardsSuporteRoute,
  AuthRelatoriosApontamentosRoute: AuthRelatoriosApontamentosRoute,
  AuthRelatoriosApontamentosProjetoRoute:
    AuthRelatoriosApontamentosProjetoRoute,
  AuthRelatoriosClienteRoute: AuthRelatoriosClienteRoute,
  AuthRelatoriosConsumoPlanosRoute: AuthRelatoriosConsumoPlanosRoute,
  AuthRelatoriosMovimentacaoDiariaRoute: AuthRelatoriosMovimentacaoDiariaRoute,
  AuthRelatoriosProdutividadeRoute: AuthRelatoriosProdutividadeRoute,
  AuthRelatoriosClientesClientIdRoute: AuthRelatoriosClientesClientIdRoute,
  AuthRelatoriosTicketsTicketIdRoute: AuthRelatoriosTicketsTicketIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
